name: Work
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '15 3,8,20 * * *'
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          persist-credentials: false

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3.0.2

      - name: Install dependencies
        run: |
          yarn

      - name: Work!
        env:
          REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
        run: |
          yarn tsx src '*' --push
